### PR TITLE
[Compilation error] Update numpy dependency to 1.23.1

### PR DESCRIPTION
**Pull request by masch**
There was a dependency version error when the project is compiled: 

```ValueError: numpy.ndarray size changed, may indicate binary incompatibilityExpected 96 from C header, got 88 from PyObject```

In order to fix it, numpy version library must be updated.

### CODE REVIEW

**Comment by masch** [comment]
@Nukesor I had the same compilation error on two different OS Linux. In order to fix it, I had to update numpy dep version to `1.23.1`. 

Let me know if there is a better fix.

**Comment by masch** [comment]
Also, I forgot to mentioned that when I run `poetry install` I get this error:

```Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

  SolverProblemError
```

In order to fix it, I run ` poetry lock --no-update` and then I can compile it.

**Comment by Nukesor** [comment]
My I ask which OS you're running?

The changes in the lockfile look kind of suspicious. 800 lines deleted don't seem right.

**Comment by Nukesor** [comment]
The current numpy version needs to be fixed until I upgraded my virtual server :<

The server is currently running python 3.7. The newest numpy version requires at least 3.8. I'll go ahead and create a PR that bumps everything to 3.10.

I planned to do this since quite a while, but didn't find the motivation to do so. Seems like it's finally time.

**Comment by Nukesor** [comment]
I just pushed an update to the pollbot's dependency on `main` :)

This MR can be closed.

**Comment by masch** [comment]
> My I ask which OS you're running?
> 
> The changes in the lockfile look kind of suspicious. 800 lines deleted don't seem right.

Yes, it was very strange but I don't know much about python and it was the way to fixed it.
I'm glad you found a better solution.

Thank you for you support!

PD: I use Fedora 36 OS.

**Pull request closed without merging**
